levaintech/sticky

.github/labels.yml, packages/sticky-docs/contented.config.js, packages/sticky-typescript/README.md, packages/sticky-typescript/package.json, packages/sticky-typescript/tsconfig.json, pnpm-lock.yaml
=> feat(typescript): add typescript to mono-repo support

README.md, packages/eslint-config/README.md, packages/eslint-config/index.js, packages/eslint-config/package.json, packages/sticky-jest/README.md, packages/sticky-jest/jest-preset.js, packages/sticky-jest/package.json, packages/sticky-jest/src/JestExtended.unit.ts, packages/sticky-jest/src/WaitForExpect.ts, packages/sticky-jest/src/WaitForExpect.unit.ts, packages/sticky-jest/src/index.ts, packages/sticky-jest/tsconfig.build.json, packages/sticky-jest/tsconfig.json, pnpm-lock.yaml
=> feat(packages): add eslint and sticky-jest

packages/sticky-turbo-jest/README.md, packages/sticky-turbo-jest/jest-preset.js, packages/sticky-turbo-jest/jest-turbo.js, packages/sticky-turbo-jest/package.json, packages/sticky-turbo/README.md, packages/sticky-turbo/package.json, packages/sticky-turbo/src/PackageJson.ts, packages/sticky-turbo/src/TurboJson.ts, packages/sticky-turbo/src/index.ts, packages/sticky-turbo/tsconfig.build.json, packages/sticky-turbo/tsconfig.json, pnpm-lock.yaml
=> feat(packages): add sticky-turbo and sticky-turbo-jest

.github/renovate.json
=> chore(renovate.json): fix configuration

.github/renovate.json, .github/workflows/oss-governance-bot.yml, .github/workflows/oss-governance-labeler.yml
=> chore(workflows): remove BIRTHDAYRESEARCH_BOT_GITHUB_TOKEN

package.json
=> chore(package): add workspaces in package.json

.github/PULL_REQUEST_TEMPLATE.md
=> chore(github): fix PR template grammar

package.json, packages/sticky-testcontainers/package.json, packages/sticky-testcontainers/src/GenericContainer.ts, packages/sticky-testcontainers/src/PostgreSqlContainer.ts, pnpm-lock.yaml
=> chore(sticky-testcontainers): replace uuid with node:crypto

.github/workflows/ci.yml, .github/workflows/release.yml, package.json
=> chore(workflows): use corepack enable pnpm

package.json, packages/sticky-docs/package.json, packages/sticky-prettier/index.js, packages/sticky-prettier/package.json, packages/sticky-testcontainers/package.json, packages/sticky-turbo/package.json, pnpm-lock.yaml
Add `prettier-plugin-packagejson` and also fix how prettier is configure with lint-staged.
=> feat(prettier): add prettier-plugin-packagejson

.github/workflows/release.yml, packages/eslint-config/package.json
Use `publishConfig.provenance=true`.
=> chore(workflows): use publishConfig.provenance=true

.github/workflows/release.yml, packages/eslint-config/package.json
=> chore(workflows): set id-token for OIDC provenance to publish

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/3-general.md, .github/renovate.json, packages/docs/contented.config.js, packages/docs/package.json, pnpm-lock.yaml
Migrate to use `@contentedjs` from https://github.com/levaintech/contented
=> chore(docs): migrate to use @contentedjs

.github/renovate.json
=> chore(workflow): update renovate.json

.github/CODEOWNERS
=> chore(workflows): add CODEOWNERS

.github/workflows/ci.yml
=> chore(workflows): enable merge_group

README.md, packages/docs/package.json
As per title, simple clean up.
=> chore(docs): do not publish docs

.github/workflows/release.yml
=> chore(workflows): fix release.yml

packages/jest/jest-preset.js
Increase jest timeout preset to 5mins from 4 mins
Fixes #
=> chore(jest): Increase jest timeout to 5mins

package.json, pnpm-lock.yaml
=> bump(typescript): major version bump to v5.3.3

package.json, pnpm-lock.yaml
=> bump(typescript): revert major version bump to v5.3.3

package.json, pnpm-lock.yaml
=> bump(deps): major ver bump ts to v5.2.2

package.json, pnpm-lock.yaml
=> chore(deps): revert ts back to 4.9.5
